### ISSUE TITLE
Compatibility with Symfony 2.8 ?

### ISSUE THREAD

**Issue by jorismulliez** [norsys/rothenberg#19]
Hi,

Since Sf 2.8 is stille maintained for ~9 months and has an en of life at 11/2019, is it possible for Rothenberg to allow it ?

I'm sorry, I'm tonew to the docker ecosystem to help you for this work...

Thanks a lot,

**Comment by mageekguy** [comment]
Hi!
Currently, we are focus to provide support for Symfony 4/flex, so adding support of Symfony 2.8 is not on the roadmap.
We prefer approving value for the present and the futur, instead of for the past (mostly because our time is precious).
However, it is possible that the support of Symfony 4/flex will allow us to support Symfony 2.8 more easily, so… maybe one day ;).
And an another solution is that someone implements Symfony 2.8 via a PR.
The door is wide open for any contribution!

**Comment by jorismulliez** [comment]
No problem !
I agree with what you say :)
Too bad for me, I'll had to upgrade my Symfony App first...

To be honest with you, I'm looking as well on lando and this pull request : https://github.com/lando/lando/pull/699

I'll try both (when available for lando) and choose the best for my case,

++
